### ISSUE TITLE
Rename `rwmh` to `rmh`

### ISSUE THREAD

**Issue by rlouf** [blackjax-devs/blackjax#102]
The implementation is general and not limited to random walks, so @AdrienCorenflos was right in naming the algorithm `mh` (for Metropolis-Hasting).

As the story goes, the "Metropolis algorithm" was also developed by [Arianna Rosenbluth](https://www.nytimes.com/2021/02/09/science/arianna-wright-dead.html) whose name is little known. I thus suggest we rename the algorithm `rmh` for `Rosenbluth-Metropolis-Hastings`.

I understand this goes against previous conventions, and it may need some getting used to for users. But if no one ever does it...

**Comment by AdrienCorenflos** [comment]
Remember to change the file header to reflect the choice of name convention

**Comment by junpenglao** [comment]
One design choice is to have `mh` being a general kernel, and have random-walk MH and `hmc` both call `mh`. This is what TFP is doing.

**Comment by rlouf** [comment]
The implementation of `mh` is already very general here, so this would be possible with very little change.

Any drawback to that design that you know of?

**Comment by rlouf** [comment]
It will actually be a bit of work to use it in `hmc` and especially `nuts`. Do we want that for the next release or later?

I suggest to start with the name change up to the `gaussian_rwrmh` algorithm as someone is working on an example notebook.

**Comment by junpenglao** [comment]
+1 starting with name change - how about just `gaussian_rmh`? gaussian is the kernel and i always consider random walk here being not a very good description (ie it shouldn't be a random walk)

**Comment by rlouf** [comment]
> I always consider random walk here being not a very good description (ie it shouldn't be a random walk) 

That is a good point, but how do we call a file that contains `gaussian_rmh` and `lognormal_rmh`? Random walk *kind of* makes sense when you oppose it to deterministic HMC proposals.
