### ISSUE TITLE
RWMH variable name conventions mismatches

### ISSUE THREAD

**Issue by AdrienCorenflos** [blackjax-devs/blackjax#108]
The variable names `logprob_fn` and `potential_fn` are used interchangeably in different places. However I think we are choosing to work in the potential space am I right? The occurences should be corrected.

@rlouf do you know of a way to catch (at minima) the docstring errors in the commit checks?

https://github.com/blackjax-devs/blackjax/blob/fe10807d04c8d1c2dcdd51e0db0ba54b4dceb88e/blackjax/inference/rwmh/base.py#L60

**Comment by rlouf** [comment]
> The variable names `logprob_fn` and `potential_fn` are used interchangeably in different places. However I think we are choosing to work in the potential space am I right? The occurences should be corrected.

You're right, and we should fix this before the next release. I am now leaning towards asking the end user of `nuts`, `hmc`, `rmh` to work in the logprob space. What do you think?

> @rlouf do you know of a way to catch (at minima) the docstring errors in the commit checks?

No but that would be nice

**Comment by rlouf** [comment]
This was addressed in #129
