### ISSUE TITLE
expose `target_accept` to `stan_warmup`?

### ISSUE THREAD

**Issue by prashjet** [blackjax-devs/blackjax#109]
For dealing with divergent transitions it can be useful to increase the target acceptance probability, e.g. in Stan's using `adapt_delta`, or in NumPyro with `target_accept_prob`. Am I right in thinking that this isn't possible with your current API?  The relevant argument seems to be set to a default value in the function,
```
def find_reasonable_step_size(
    ...
    target_accept: float = 0.65,
) -> float:
```
but this is not exposed to `stan_warmup`.

Is there a reason for this choice and/or another approach you recommend for dealing with divergences? Alternatively, if you agree to exposing `target_accept` to `stan_warmup`, I'd be happy to put in a small PR.

Thanks for the great library!

**Comment by rlouf** [comment]
That's a good point, there's no reason why we wouldn't expose
it. Please open a PR!
