### ISSUE TITLE
small error in Introduction.ipynb: you accidently use the wrong kernel

### ISSUE THREAD

**Issue by murphyk** [blackjax-devs/blackjax#112]
In cell 19 of [Introduction.ipynb](https://github.com/blackjax-devs/blackjax/blob/main/notebooks/Introduction.ipynb) you create `kernel` using STAN warmup, but in cell 20, you use the old `nuts_kernel` which created earlier without using warmup.

**Comment by rlouf** [comment]
You're right, and it also seems that there is a bug in the Stan warmup as I only get divergences when I use the kernel built with the parameters returned by the warmup ! This should not happen with such a simple model. I'll open a new issue and leave this one open.

**Comment by rlouf** [comment]
This was solved with https://github.com/blackjax-devs/blackjax/commit/a29272d76a3340e470751b7926f37aa3eae66a37. It also appears that previous work on adaptation solved all known issues with it. Great news!
