### ISSUE TITLE
Add new CheesHMC sampler by Hoffman et al

### ISSUE THREAD

**Issue by twiecki** [blackjax-devs/blackjax#12]
http://proceedings.mlr.press/v130/hoffman21a/hoffman21a.pdf

**Comment by rlouf** [comment]
That's a good idea! The code has been in TFP for a little while, can't wait to read the paper :)

**Comment by rlouf** [comment]
So I had a quick look. It is a new warmup scheme for the most part and here's what would be necessary:
1. a jittered version of HMC, which is trivial to implement here;
2. Dual averaging;
3. Their tuning algorithm for the scale of the trajectory length, `T`, which requires the Adam optimizer.

(2) is part of the Stan warmup and I already have an implementation of Adam in MCX that I can just copy/paste. Will implement once we have a drop in replacement for NUTS + Stan warmup.
