### ISSUE TITLE
Use `jupytext`-compatible markdown files instead of notebooks?

### ISSUE THREAD

**Issue by rlouf** [blackjax-devs/blackjax#128]
Notebooks don't work well with versioning, but the markdown files produced by `jupytext` do.  I suggest we only version the markdown versions in the repository, and render the notebooks for the documentation.

_Edit:_ We use [MyST-nb](https://myst-nb.readthedocs.io/en/latest/) to build documentation from notebooks, and it does support notebooks in jupytext format. It is just a matter of converting the notebooks and configure the build in CI.

**Comment by bkktimber** [comment]
I see. I just noticed you have assigned yourself to this issue. If you've already started working on this issue already, I can take a look at other issues. thank you.

**Comment by bkktimber** [comment]
Got it. Thank you!
