### ISSUE TITLE
No module named 'blackjax.inference.smc' when running TemperedSMC.ipynb

### ISSUE THREAD

**Issue by murphyk** [blackjax-devs/blackjax#147]
I tried to run https://github.com/blackjax-devs/blackjax/blob/main/notebooks/TemperedSMC.ipynb in colab, after `pip install blackjax` (v0.2.1). I get the error `No module named 'blackjax.inference.smc'`.  If I comment out that line I later get the error `No module named 'blackjax.tempered_smc'`.

![Screen Shot 2021-11-03 at 5 13 07 PM](https://user-images.githubusercontent.com/4632336/140236173-651b8120-8b06-429a-965f-805bf6c8a0aa.png)
.

**Comment by rlouf** [comment]
That's correct. You would need to install the version that corresponds to the latest git commit (`pip install git+https://github.com/blackjax-devs/blackjax`). I haven't cut a release for SMC yet, but probably should.

**Comment by rlouf** [comment]
Closing as I just cut a new release that includes Tempered SMC
