### ISSUE TITLE
small documentation error in TemperedSMC.ipynb

### ISSUE THREAD

**Issue by murphyk** [blackjax-devs/blackjax#148]
The notebook https://github.com/blackjax-devs/blackjax/blob/main/notebooks/TemperedSMC.ipynb
says the potential is $p_0(x) = \mathcal{N}(x \mid 0_2, I_2)$ and a potential function $V(x) = (||x||^2 - 1)^2$.
But in fact the example hard-codes the assumption that the dimensionality is $d=1$ as is apparent from `linspace` below (and the HMC kernel definitions later on).

![Screen Shot 2021-11-03 at 5 23 44 PM](https://user-images.githubusercontent.com/4632336/140236987-42ce7069-ce35-4d1c-820b-8e3e433327de.png)

**Comment by rlouf** [comment]
Thank you for pointing this out ! @AdrienCorenflos

**Comment by AdrienCorenflos** [comment]
Thanks I'm at a seminar will check tomorrow
