### ISSUE TITLE
JIT internal callable

### ISSUE THREAD

**Issue by junpenglao** [blackjax-devs/blackjax#161]
IIUC (see eg dicussion [on jax](https://github.com/google/jax/discussions/5199) there is no harm jitting inner function. The benefit is that if user forget to jit the sampling is still fast.

Related to https://github.com/blackjax-devs/blackjax/pull/159, we can even be precise on specifying the JIT pattern with `static_argnums` or `static_argnames` depending on the input.

**Comment by rlouf** [comment]
You mean that there is no penalty in "over jitting" ?

**Comment by rlouf** [comment]
I had a look around in other jax based libraries and the norm seems to be to leave the choice to the user. Closing for now, feel free to move to discussions if you have good arguments in favor.
