### ISSUE TITLE
MALA Sampler?

### ISSUE THREAD

**Issue by HanGuo97** [blackjax-devs/blackjax#182]
Hi, I noticed that we have a `mala.py` planned in https://github.com/blackjax-devs/blackjax/pull/159 . However, it seems like this didn't end up being implemented in the library. I'm curious if there is any plan to add MALA?

It also seems like MALA can be implemented as HMC [with just one leapfrog step](https://github.com/tensorflow/probability/blob/main/spinoffs/oryx/oryx/experimental/mcmc/kernels.py#L191-L194). Would that be the case here as well -- by setting `num_integration_steps=1` in `hmc`? 

Thanks in advance for the help!

**Comment by rlouf** [comment]
Thank you for your interest. There is a short term plan to add MALA indeed!

**Comment by rlouf** [comment]
Implemented in #152

**Comment by HanGuo97** [comment]
That's awesome, thanks!
