### ISSUE TITLE
Docs and examples using refactored APIs while most recent release still using the old ones

### ISSUE THREAD

**Issue by drabbit17** [blackjax-devs/blackjax#185]
### Bug Description

I was trying to reproduce the [Logistic Regression example](https://blackjax-devs.github.io/blackjax/examples/LogisticRegression.html) using version 0.3.0 and got the following error when running line `rmh_sampler = blackjax.rmh(logprob_fn, sigma=jnp.ones(M) * 0.7)`. 

![Screenshot from 2022-03-27 23-33-55](https://user-images.githubusercontent.com/11328307/160303970-540d3aaf-1c65-4cbb-aeca-a25500f50965.png)
![Screenshot from 2022-03-27 23-34-13](https://user-images.githubusercontent.com/11328307/160303985-67fff344-b887-4853-acb9-94479aabb731.png)

I also tried to run the other examples in the [Introduction notebook](https://github.com/blackjax-devs/blackjax/blob/main/examples/Introduction.ipynb) as well as the one in the README without success.

It took me a while to realise that the APIs in the last release 0.3.0 have been considerably refactored with [!159](https://github.com/blackjax-devs/blackjax/pull/159) and that all the docs are using the new APIs. 

I think that it would be nice if you could specify in the README as well as in the main doc that the examples are all using a still to be released version and that to make them work you need to install directly from a local clone of the project.

#### Versions
BlackJAX 0.3.0
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0]
Jax 0.2.28
Jaxlib 0.1.76

**Comment by rlouf** [comment]
Thank you for raising the issue. I am going to do even better than this and release a new version of the package!

**Comment by rlouf** [comment]
Done!
