### ISSUE TITLE
Relax jax and jaxlib version requirements?

### ISSUE THREAD

**Issue by hriebl** [blackjax-devs/blackjax#19]
It's currently a bit annoying to use BlackJAX with other JAX-dependent libraries, because the version requirements of BlackJAX are fixed to `jax==0.2.7` and ` jaxlib==0.1.57`. Maybe they can be relaxed a bit?

Cheers!

**Comment by rlouf** [comment]
Of course, we started working on this a while back and haven't updated the requirements recently. The versions need to be relaxed manually because of frequent breaking changes in JAX. Will do that asap!

**Comment by rlouf** [comment]
Fixed with #20 merged on master
