### ISSUE TITLE
Add PR templates

### ISSUE THREAD

**Issue by rlouf** [blackjax-devs/blackjax#199]
We should add a PR template with:
- Guide to good commit titles
- List of things to check when adding a new algorithm (example notebook, tests, docs, etc)
- Etc

**Comment by bkktimber** [comment]
Hello, I would like to contribute to this issue and already create [PR](https://github.com/blackjax-devs/blackjax/pull/230).

I am new the the OSS community and also Bayesian. I would like to to start making contribution in both fields and hope this is a good place to start.

Any feedback/suggestion is welcome. Thank you!
