### ISSUE TITLE
Blackjax for Apple M1 GPU?

### ISSUE THREAD

**Issue by fbarfi** [blackjax-devs/blackjax#200]
### Bug Description

 there is now a jax and jaxlib for apple M1, will balckjax be updated so that it can use the GPU on M1? I tried it with CPU and it works well. Thanks. 

#### Steps/Code to Reproduce

```
Sample code to reproduce the problem
```

**Comment by rlouf** [comment]
You need to install Jax and Jaxlib manually when installing blackjax (it is not included in requirements) exactly because of this kind of situation. Just instal the right versions and you should be fine. If not please come open an issue!

**Comment by fbarfi** [comment]
@rlouf thanks for your quick response.
I did install all three and here is the config:
jaxlib  : 0.3.0
jax     : 0.3.4
blackjax: 0.4.0

The CPU works great on my Apple M1 Max. 
the GPU is not detected.

**Comment by rlouf** [comment]
You should check in with the JAX team, we have absolutely no control over this part of JAX!

**Comment by fbarfi** [comment]
thanks
