### ISSUE TITLE
Replace `jax.tree_util.tree_multimap` with `jax.tree_util.tree_map`

### ISSUE THREAD

**Issue by rlouf** [blackjax-devs/blackjax#202]
The former has been deprecated in[v0.3.5](https://github.com/google/jax/releases/tag/jax-v0.3.5)

**Comment by hriebl** [comment]
I think this is as easy as replacing the calls to `tree_multimap` with calls to `tree_map`. I could provide a PR for that, but that would of course mean dropping support for JAX < 0.3.5. Would you be okay with that?

**Comment by rlouf** [comment]
Yes, you can go ahead, thank you!
