### ISSUE TITLE
Install currently fails

### ISSUE THREAD

**Issue by ColCarroll** [blackjax-devs/blackjax#212]
Hey! Looks like the install currently fails (see, for example, the PyMC build https://github.com/pymc-devs/pymc/runs/6595662934?check_suite_focus=true#step:8:99), due to jaxopt being added in https://github.com/blackjax-devs/blackjax/pull/194

Happy to make a PR, but not sure if you want to update the README to `pip install jax jaxlib jaxopt`, or update the setup.py. I checked, and [jaxopt requires jax and jaxlib](https://github.com/google/jaxopt/blob/main/requirements.txt), so adding it to the requirements.txt seems to go against your desire of _not_ including them as a requirement.

**Comment by rlouf** [comment]
Unless @junpenglao objects we can go ahead and add `jax` `jaxlib` and `jaxopt` to the requirements, and refer to the JAX documentation in the README for those who want to use blackjax on GPU. Would you mind opening a PR for that?
