### ISSUE TITLE
makes window_adaptation more vmap friendly

### ISSUE THREAD

**Issue by junpenglao** [blackjax-devs/blackjax#215]
Currently we cannot vmap `window_adaptation` as the one of the return is a `kernel`
https://github.com/blackjax-devs/blackjax/blob/f4221d041902b472095983cd83edffb76a395f51/blackjax/kernels.py#L584-L587

Proposal to add a kwarg `return_kernel=True` to `window_adaptation`:

```python
 step_size, inverse_mass_matrix = final(last_warmup_state) 
 if return_kernel:
     kernel = kernel_factory(step_size, inverse_mass_matrix) 
     return last_chain_state, kernel, warmup_chain 
 else:
     return last_chain_state, (step_size, inverse_mass_matrix), warmup_chain 
```

**Comment by rlouf** [comment]
I've never been a big fan on this API to be honest, I expect it to return the parameters every time I use it. So maybe we should do just that.

**Comment by rlouf** [comment]
Linked to #171. Should be addressed together.
