### ISSUE TITLE
 ModuleNotFoundError: No module named 'blackjax.optimizers'

### ISSUE THREAD

**Issue by xaviergonzalez** [blackjax-devs/blackjax#223]
### Bug Description

I am trying to use blackjax in colab. Yesterday, it was working fine. Now, when I try to import blackjax, I get the following error: ModuleNotFoundError: No module named 'blackjax.optimizers'

#### Steps/Code to Reproduce

```
! pip install blackjax
import blackjax
```

#### Expected Results

No error messages, and blackjax loads.

#### Actual Results

ModuleNotFoundError: No module named 'blackjax.optimizers'

#### Versions

Python 3.7.13 (default, Apr 24 2022, 01:04:09) 
[GCC 7.5.0]
Jax 0.3.8
Jaxlib 0.3.7

**Comment by karm-patel** [comment]
Same error! 

**Versions:**
Python 3.7.13
blackjax               0.8.1
jax                    0.3.13
jaxlib                 0.3.10

**Comment by rlouf** [comment]
Can you try with blackjax 0.8.0 ? @junpenglao

**Comment by xaviergonzalez** [comment]
> Can you try with blackjax 0.8.0 ? @junpenglao

I'm getting the same error with the following code

```
! pip install blackjax==0.8.0
import blackjax
```

**Comment by rlouf** [comment]
This should be solved in 0.8.2 !

**Comment by murphyk** [comment]
It does work if you first install jaxopt, like this:
<img width="958" alt="Screen Shot 2022-06-20 at 8 48 31 AM" src="https://user-images.githubusercontent.com/4632336/174638865-1cd92181-993d-4e41-8205-358710af83b7.png">

But if you install blackjax before jaxopt it will fail

<img width="959" alt="Screen Shot 2022-06-20 at 8 46 05 AM" src="https://user-images.githubusercontent.com/4632336/174638960-bcc7d035-afaf-4b91-a2d0-563991f16538.png">

**Comment by rlouf** [comment]
This is really strange, I'll try to reproduce it locally. I'll also include `jax` and `jaxopt` in the dependencies in the next release.
