### ISSUE TITLE
Check library import after Pypi upload

### ISSUE THREAD

**Issue by rlouf** [blackjax-devs/blackjax#225]
Should allow us catch issues such as #223.

**Comment by junpenglao** [comment]
@thomaspinder Could you add `jaxopt` to your dependence? Sorry about breaking your side!

**Comment by thomaspinder** [comment]
Thanks! That seems to have fixed it.

Is there any view to adding `jaxopt` to the dependencies of BlackJax?

**Comment by rlouf** [comment]
Yes this was raised in #212. We're ready to include `jax`, `jaxlib` and `jaxopt` as dependencies now.

**Comment by rlouf** [comment]
[PyMC](https://github.com/pymc-devs/pymc/blob/be048a495b32a09c49ec8d3e8a95d4f5e4290d2a/.github/workflows/release.yml#L43) checks that the package has been uploaded. We can run `python -c "import blackjax"` afterwards.

**Comment by rlouf** [comment]
The current test mysteriously fail with:

```bash
ERROR: Could not find a version that satisfies the requirement blackjax==.8.3 (from versions: 0.1, 0.2, 0.2.1, 0.3.0, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.8.1, 0.8.2, 0.8.3)
ERROR: No matching distribution found for blackjax==.8.3
```
