### ISSUE TITLE
Use the new marginal sampler for latent gaussian models in the GP notebook

### ISSUE THREAD

**Issue by rlouf** [blackjax-devs/blackjax#238]
See #228

**Comment by juanitorduz** [comment]
Hi! I would like to take a beginner-friendly issue to contribute to the project. This one seems like a good one (based on my naive judgment). To clarify the scope, the idea is to use the data from https://blackjax-devs.github.io/blackjax/examples/GP_EllipticalSliceSampler.html to illustrate the implementation introduced in https://github.com/blackjax-devs/blackjax/pull/247 ?

**Comment by rlouf** [comment]
Yes, that's correct!

**Comment by juanitorduz** [comment]
Thanks! I will try it out (although I might be slower then other contributors 🙈 )

**Comment by rlouf** [comment]
Thank you for your interest! Don't worry, I'm probably slower than most maintainers :)
