### ISSUE TITLE
Add example notebook of change of variable in HMC

### ISSUE THREAD

**Issue by karm-patel** [blackjax-devs/blackjax#252]
Hello Team,

In HMC, the latent variable must be in an unconstrained space. Perhaps stan, pymc & numpyro are doing the **change of variable** trick under the hood. In BlackJAX we need to apply this trick in the `joint_logprob()` function manually and I haven't seen an example of the same in the documentation.  

However, In toy examples (i.e - coin toss problem, linear regression), I don't see much difference between constrained and unconstrained support. Thus, I have implemented a hierarchical binomial model for the rat tumor problem ([**hierarchical_binom_rats.ipynb**](https://drive.google.com/file/d/14nhCNpo-TyTvy785jeUotdcaNb8f0ZwP/view?usp=sharing)), Where I've shown that if we don't use a change of variable then result are terrible.

In the above notebook, I can highlight two major things
1. Change of variable in HMC
2. How to use arviz with BlackJAX to quickly check diagnostics of MCMC.

If the above notebooks look helpful, then I can reformat the notebook and create a PR.

**Comment by rlouf** [comment]
That looks awesome! I wanted to add a simple example with aesara/aeppl so I'll probably add it to this notebooks when merged. Looking forward to the PR!
