### ISSUE TITLE
Installation failure: step_size.py can't import blackjax.optimizers.dual_averaging

### ISSUE THREAD

**Issue by renniek** [blackjax-devs/blackjax#257]
**Bug**:  When trying to import blackjax after installation, it fails and gives the following error: "ImportError: cannot import name 'optimizers' from 'blackjax' (/usr/local/lib/python3.7/dist-packages/blackjax/__init__.py)". This was noted in the comments of Issue #223 as occurring when you install blackjax before installing jaxopt, but even when I first install jaxopt, I am running into this issue.

**Sample code to reproduce the problem**:

! pip install jaxopt
! pip install blackjax
import blackjax

I noticed that when I run these commands in terminal, and then run python in terminal and import blackjax, I do not have this error – only when I am on Google colab. I also have no issue in Spyder, so it seems Google colab specific

Thank you in advance!

**Comment by rlouf** [comment]
Can you please print the version number requested in the bug issue template?

**Comment by junpenglao** [comment]
I cannot reproduce it in Colab.

**Comment by renniek** [comment]
When I restarted runtime and ran everything in one code block it's now working – not sure what was happening but glad it's now working!
