### ISSUE TITLE
SMC + RMH doesn't work for multivariable posterior 

### ISSUE THREAD

**Issue by ciguaran** [blackjax-devs/blackjax#258]
### Bug Description
Hi team, I am trying to run one iteration of the base implementation of SMC with a simple RMH kernel. When enconding a multivariable posterior, I am constructing a PyTree (a list) with one element per posterior variable as is done here: https://github.com/blackjax-devs/blackjax/blob/d440031bfc15c87fc8d38c670b82249610f61ae5/tests/test_tempered_smc.py#L63 . I am getting an exception, which seems reasonable. The example in examples.py uses a univariate posterior, so particles are represented as an array (not a list).

#### Steps/Code to Reproduce

https://gist.github.com/ciguaran/0c0af6c79051cf8c9558fbe71b42ec75

#### Expected Results
Particles from posterior

#### Actual Results
```
--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ciguaran/personal/blackjax_fork/tests/multivariable_smc_mh.py", line 43, in <module>
    updated_particles, _ = functools.partial(
  File "/Users/ciguaran/personal/blackjax_fork/blackjax/smc/base.py", line 115, in one_step
    proposed_states, _ = jax.lax.scan(mcmc_body_fn, mcmc_state, keys)
  File "/Users/ciguaran/personal/blackjax_fork/blackjax/smc/base.py", line 106, in mcmc_body_fn
    new_particles, _ = jax.vmap(mcmc_kernel, in_axes=(0, 0))(
  File "/Users/ciguaran/personal/blackjax_fork/blackjax/kernels.py", line 705, in step_fn
    return step(
  File "/Users/ciguaran/personal/blackjax_fork/blackjax/mcmc/rmh.py", line 85, in one_step
    return kernel(rng_key, state)
  File "/Users/ciguaran/personal/blackjax_fork/blackjax/mcmc/rmh.py", line 165, in kernel
    delta = acceptance_probability(state, new_state)
  File "/Users/ciguaran/personal/blackjax_fork/blackjax/mcmc/rmh.py", line 128, in acceptance_probability
    return proposal.log_probability - state.log_probability
TypeError: unsupported operand type(s) for -: 'list' and 'list'
```

#### Versions

BlackJAX 0.8.2
Python 3.8.5 (default, Jan  8 2021, 13:12:50) 
[Clang 12.0.0 (clang-1200.0.32.27)]
Jax 0.3.14
Jaxlib 0.3.14

Running on latest main commit: d440031bfc15c87fc8d38c670b82249610f61ae5

**Comment by junpenglao** [comment]
We require log_prob_fn output a (batch of) scalar output, so a quick fix is to change:
```python
    return sum(jax.tree_map(single_particle_logprobfn, position))
```

**Comment by ciguaran** [comment]
Thank you so much. I wonder if there's a way to somehow document those properties on inputs. logprob_fn is typed as Callable, but that is not enough. Maybe type aliases with comments? I mean having a type alias LogProbFn = Callable but in the type definition documenting what kind of callable is expected?

**Comment by rlouf** [comment]
We can specify the output type of `Callable`s, and it would be a good idea. Would you mind opening an issue ?

**Comment by ciguaran** [comment]
Done, https://github.com/blackjax-devs/blackjax/issues/262, closing this one.
