### ISSUE TITLE
Need to cut another release for 0.8.3

### ISSUE THREAD

**Issue by canyon289** [blackjax-devs/blackjax#265]
### Bug Description
cc @junpenglao 

Up front apologies for terrible bug report, I found it on my work laptop so I can't paste the results here.

TLDR is the 0.8.2 release is raising 
`cannot import name optimizers from blackjax` when I try and use that release. The bug has been fixed on main, and when I install from bleeding edge things work fine.

#### Steps/Code to Reproduce
1. Install latest release of blackjax
2. Try and sample stuff, in particular using PyMC V4 interface

#### Expected Results
Sampling works

#### Actual Results
I get an exception

#### Versions
BlackJax 0.8.2

**Comment by junpenglao** [comment]
+1 to cut a new release. Although very puzzling that pip install works on a new conda env on my laptop, but not on colab...

**Comment by rlouf** [comment]
I just cut a new release, hopefully this solves it!

**Comment by canyon289** [comment]
Geez you guys are fast.

Thanks!

**Comment by rlouf** [comment]
Np. Let us know if this doesn't solve it!

**Comment by junpenglao** [comment]
I notice there is a typo in the release number, and thus the release is not appear correctly on pip - we need to redo it
