### ISSUE TITLE
Add community resources: contributing guide, code of conduct, governance?

### ISSUE THREAD

**Issue by OriolAbril** [blackjax-devs/blackjax#28]
I noticed there are already some issues labeled as "good first issue", but without a contributing guide (plus a code of conduct to establish a baseline on how to interact) they can't really be good first issues, at most they can be good first issue _for someone who has contributed to other projects but not yet to blackjax_.

While I was here, I have no idea if there are some non-written rules about collaboration and decision making between the different projects and people involved but it may also be worth it to add a governance doc at some point, even if a couple sentences.

I will probably be able to review anything related to this on a day/week timescale but I don't think I can send a PR in the near future.

**Comment by rlouf** [comment]
@junpenglao we should formalize all of this before v1 is released and as the library is getting more attention.

**Comment by rlouf** [comment]
If anyone is reading this and interested to know more, this project fits in the ["Houseplant" archetype](https://github.com/OpenTechStrategies/open-source-archetypes/blob/main/arch-houseplant.ltx) and follows the BDFL model of governance with myself as the dictator. This can be re-evaluated later but no need to formalise things any further at this point.

**Comment by OriolAbril** [comment]
Would it be ok if I send a PR to add a GOVERNANCE.md with:

```
Blackjax fits in the ["Houseplant" archetype](https://github.com/OpenTechStrategies/open-source-archetypes/blob/main/arch-houseplant.ltx)
and follows the BDFL model of governance with @rlouf as the benevolent dictator. 
```

**Comment by rlouf** [comment]
By all means!
