### ISSUE TITLE
 Names of lower-level implementations are inconsistent 

### ISSUE THREAD

**Issue by rlouf** [blackjax-devs/blackjax#280]
e.g. `step_fn`, `kernel`, etc. We should also be more explicit names like `build_kernel` of `build_step_fn`. Indeed 

```python
blackjax.mcmc.nuts.kernel()
```

is confusing and should be replaced with

```python
blackjax.mcmc.nuts.build_kernel()
```

And the name should be propagated downstream to aliases in the high level kernel:

```python
blackjax.nuts.build_kernel()
```

**Comment by rlouf** [comment]
We first need to better define our vocabulary. What do we call a kernel, a step function, etc.

**Comment by albcab** [comment]
For MCMC/SMC/SGMCMC: I like `kernel` because it references Markov or general transition kernels, `build_kernel` or `kernel_gn` are good options to avoid confusion. Instead of `one_step` what about `iterator`? Also `init_fn` and `step_fn` are good names.

**Comment by rlouf** [comment]
Let's avoid `iterator` as it has a well-defined meaning in Python already. My main concern when it comes to naming is the distinction between the "elementary" step functions that take the log-density as well as algorithm parameters, and the specialized step function that only take the PRNG key and current position.

**Comment by albcab** [comment]
What about the following naming changes?
`kernel` -> `build_kernel`
`one_step` -> `kernel`
`step` -> `kernel`
`init_fn` -> `init_fn`
`step_fn` -> `step_fn`

**Comment by rlouf** [comment]
This all seems reasonable to me. @junpenglao ?
