### ISSUE TITLE
Refactor the potential fun flip in HMC 

### ISSUE THREAD

**Issue by junpenglao** [blackjax-devs/blackjax#284]
We internally flip the sign of `log_prob_fn` and use `potential_fun` instead - this start to create more headache in the code base, we should refactor to use `log_prob_fn` directly.

**Comment by rlouf** [comment]
I'm not sure I'm ready to forego the physical system analogy in the code.

**Comment by junpenglao** [comment]
Think of it this way: you can get rid of 100s lines of codes

**Comment by rlouf** [comment]
100s? I see max 20?

**Comment by rlouf** [comment]
Even if it doesn't remove many lines of code this is nevertheless a simplifying change. You were right, adding this to the `1.0` milestone as this would be a breaking change for those using the internals.
