### ISSUE TITLE
Improve MEADS implementation

### ISSUE THREAD

**Issue by junpenglao** [blackjax-devs/blackjax#285]
- [ ] Improve some shape handling related to batch dimension (e.g., https://github.com/blackjax-devs/blackjax/pull/229/files#r973546362)
- [ ] change the per variable step size to using scalar step size and diag mass matrix

**Comment by rlouf** [comment]
What did you have in mind for 1?

**Comment by albcab** [comment]
What about 
```python
X = jax.vmap(lambda m: jax.flatten_util.ravel_pytree(m)[0])(matrix)
```
instead of
```python
X = jnp.vstack(
    [
        leaf.reshape(leaf.shape[0], -1).T
        for leaf in jax.tree_util.tree_leaves(matrix)
    ]
).T
```
for 1?

I've realized pmapping makes no sense in this algorithm so I'll remove `batch_fn` (`divergence_threshold` too).
