### ISSUE TITLE
Refactor the HierarchicalBNN example

### ISSUE THREAD

**Issue by rlouf** [blackjax-devs/blackjax#305]
- Use `flax` to build the neural network;
- The function `get_predictions` can be optimized, this may substantially speed up the notebook

**Comment by junpenglao** [comment]
Also since the example imports both `tensorflow_probability.distributions` and `distrax`, which have duplicate functionalities.

**Comment by rlouf** [comment]
I have a quick and dirty refactor and it runs much faster.

**Comment by rlouf** [comment]
Should be trivial after: https://github.com/blackjax-devs/blackjax/discussions/360#discussioncomment-3756412

**Comment by rlouf** [comment]
Fixed in #362
