### ISSUE TITLE
Add a conda-forge recipe for Blackjax

### ISSUE THREAD

**Issue by rlouf** [blackjax-devs/blackjax#315]

**Comment by dirmeier** [comment]
Hey, I'd like to have Blackjax installable via conda, so I could do this. Cheers, S

**Comment by dirmeier** [comment]
Ciao @rlouf, would you mind adding a LICENSE file in the tarball and bumping the version? It's needed for conda-forge afair. Otherwise I can just add it to the recipe if you prefer not to have it there. Thanks!

**Comment by rlouf** [comment]
I pushed the change in #344 and cut a new release; we'll just have to check the tarball once 0.9.1 is published on Pypi.

**Comment by dirmeier** [comment]
Great, thanks!

**Comment by dirmeier** [comment]
You should be able to use conda-forge now for installation: https://github.com/conda-forge/blackjax-feedstock

**Comment by rlouf** [comment]
That's awesome, thank you! Can I and @junpenglao be made admin of the repo?

**Comment by dirmeier** [comment]
You'll need to create a PR that adds you as a maintainer (which boils down to merging automatic PRs). See here: https://conda-forge.org/docs/orga/guidelines.html#becoming-a-maintainer

**Comment by rlouf** [comment]
I opened two PRs, you should have gotten notifications. Otherwise: https://github.com/conda-forge/blackjax-feedstock/pulls

Thank you again!
