### ISSUE TITLE
Rewrite the MNIST MLP example with Flax

### ISSUE THREAD

**Issue by rlouf** [blackjax-devs/blackjax#326]
https://blackjax-devs.github.io/blackjax/examples/SGMCMC.html

And add SgHMC back!

**Comment by zaxtax** [comment]
Related to #291

**Comment by rlouf** [comment]
Want to do it too?

**Comment by zaxtax** [comment]
@rlouf yea!

**Comment by rlouf** [comment]
Not that you need it, but it should be trivial based on this: https://github.com/blackjax-devs/blackjax/discussions/360#discussioncomment-3756412

**Comment by zaxtax** [comment]
@rlouf I didn't but there are lots of good ideas to take from that!
