### ISSUE TITLE
Images are not displayed in the documentation

### ISSUE THREAD

**Issue by rlouf** [blackjax-devs/blackjax#333]
This doesn't seem to be a bug on our end, even the documentation of MyST-NB currently doesn't display the pictures: https://myst-nb.readthedocs.io/en/v0.8.4/examples/basic.html

**Comment by junpenglao** [comment]
Other cell output like `print(...)` are not displayed currently as well.

**Comment by rlouf** [comment]
Oh found it, I turned off notebook exécution locally and that got committed.
