### ISSUE TITLE
Typo in example introduction for the window adaptation part

### ISSUE THREAD

**Issue by oarriaga** [blackjax-devs/blackjax#366]
Hi hi! The [original jupyter documentation](https://github.com/blackjax-devs/blackjax/blob/fb919c819a27ff6fd8df93da0e9126be68f00425/examples/Introduction.ipynb) for the introduction reused the state and kernel in cell 17 outputted from the window adaptation warmup in cell 16.

However, the [current html documentation](https://blackjax-devs.github.io/blackjax/examples/Introduction.html) seems to use an entirely new kernel `nuts.step` with the previous state `initial_state`. If this is a typo I could send a quick PR changing the markdown file back to the original jupyter documentation form. 

Thanks!

**Comment by rlouf** [comment]
This is totally a typo!
