### ISSUE TITLE
Dead link to examples

### ISSUE THREAD

**Issue by xidulu** [blackjax-devs/blackjax#443]
### Describe the issue as clearly as possible:

https://github.com/blackjax-devs/blackjax/blob/main/examples/Introduction.md

### Steps/code to reproduce the bug:

```python
N/A
```

### Expected result:

```shell
N/A
```

### Error message:

```shell
N/A
```

### Blackjax/JAX/jaxlib/Python version information:

```python
N/A
```

**Comment by rlouf** [comment]
Where's that link located? Examples were moved to /docs recently.

**Comment by xidulu** [comment]
<img width="1057" alt="Screen Shot 2023-01-11 at 01 14 59" src="https://user-images.githubusercontent.com/26022201/211765891-956d906b-eef3-4ba4-9632-d0fee76832c8.png">
This link

**Comment by rlouf** [comment]
Thanks for reporting this, I replace the link with a link to the documentaiton.
