### ISSUE TITLE
Can't run tests in main due to `from blackjax._version import __version__`

### ISSUE THREAD

**Issue by ciguaran** [blackjax-devs/blackjax#445]
### Describe the issue as clearly as possible:

Pulling latest main, can't run tests since can't find _version module

### Steps/code to reproduce the bug:

```python
pytest
```

### Expected result:

```shell
Tests running
```

### Error message:

```shell
../../.pyenv/versions/3.8.5/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_uturn.py:6: in <module>
    from blackjax.mcmc.metrics import gaussian_euclidean
blackjax/__init__.py:1: in <module>
    from blackjax._version import __version__
E   ModuleNotFoundError: No module named 'blackjax._version'
```

### Blackjax/JAX/jaxlib/Python version information:

```python
jaxlib 0.3.22
jax 0.4.1
Python 3.8.5 
commit 3649ef55f0d44477b412942ea1729fda38584480
```

**Comment by rlouf** [comment]
How did you install the dev environment?

**Comment by ciguaran** [comment]
git clone, `pip install -r requirements.txt`.
Also tried `pip install .`

**Comment by rlouf** [comment]
Ok that's a problem, I'll take a look. In the meantime you can add a mock `blackjax/_version.py` with `__version__ = "0.0.0."`.

That's because of what we use to determine the version from the latest git tag.

**Comment by junpenglao** [comment]
This is already fixed.
