### ISSUE TITLE
Potential memory leak when running inference loop in another loop

### ISSUE THREAD

**Issue by kstensbo** [blackjax-devs/blackjax#486]
### Describe the issue as clearly as possible:

I have encountered an unexpected behaviour with `blackjax` when running the `inference_loop` defined in the introductory examples within another for-loop. 

Say I want to generate 1000 samples using the NUTS sampler. I can either run `inference_loop(..., num_samples=1000)`, or, to be really inefficient, I can run `for _ in range(1000): inference_loop(..., num_samples=1)` (and collect the generated samples, of course). Unsurprisingly, the for-loop version takes much, much longer to run, but surprisingly, the memory usage (as reported by `htop`) of the process keeps increasing for every outer iteration. Is this to be expected, and if so, is there a way I can reset everything at every iteration? Redefining everything at each iteration of the for-loop does not help, and neither does `del` nor `gc.collect()`.

The attached example, taken entirely from "A Quick Introduction to Blackjax" with the expectation of the final for-loop, shows this behaviour (to see it, monitor the memory consumption of the script in, say, `htop`).

I know this usage might be a little unorthodox, but I am testing a setup where the `logdensity` is being learnt with updates to it happening in the for-loop. Thus, I need to repeatedly stop sampling, update `logdensity`, and then resume sampling again. 

### Steps/code to reproduce the bug:

```python
import jax
import jax.numpy as jnp
import jax.scipy.stats as stats
import numpy as np

import blackjax

loc, scale = 10, 20
observed = np.random.normal(loc, scale, size=1_000)

def logdensity_fn(loc, log_scale, observed=observed):
    """Univariate Normal"""
    scale = jnp.exp(log_scale)
    logpdf = stats.norm.logpdf(observed, loc, scale)
    return jnp.sum(logpdf)

logdensity = lambda x: logdensity_fn(**x)

def inference_loop(rng_key, kernel, initial_state, num_samples):
    @jax.jit
    def one_step(state, rng_key):
        state, _ = kernel(rng_key, state)
        return state, state

    keys = jax.random.split(rng_key, num_samples)
    _, states = jax.lax.scan(one_step, initial_state, keys)

    return states

# Build the kernel:
inv_mass_matrix = np.array([0.5, 0.01])
step_size = 1e-3

nuts = blackjax.nuts(logdensity, step_size, inv_mass_matrix)
kernel = nuts.step

initial_position = {"loc": 1.0, "log_scale": 1.0}
state = nuts.init(initial_position)

key = jax.random.PRNGKey(0)

# This is fast and memory consumption stays low:
states = inference_loop(key, kernel, state, 1_000)

# This is slow, and the memory consumption keeps increasing:
for _ in range(1_000):
    key, rng_key = jax.random.split(key)
    states = inference_loop(rng_key, kernel, state, 1)
```

### Expected result:

```shell
I would expect the memory consumption (as reported by `htop`) to stay constant during iterations of the for-loop. Instead, memory consumption keeps increasing.
```

### Blackjax/JAX/jaxlib/Python version information:

```python
BlackJAX 0.9.6.post131
Python 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0]
Jax 0.4.1
Jaxlib 0.4.1
```

**Comment by albcab** [comment]
Try jitting `one_step` only once, outside the `inference_loop` function:

```python
@jax.jit
def one_step(state, rng_key):
    state, _ = kernel(rng_key, state)
    return state, state

def inference_loop(rng_key, kernel, initial_state, num_samples):

    keys = jax.random.split(rng_key, num_samples)
    _, states = jax.lax.scan(one_step, initial_state, keys)

    return states
```

**Comment by albcab** [comment]
Notice you are returning the full sequence of states (not only the last one), so each time you call `one_step` you are doing it will a different sized input, allocating new memory for each call!

**Comment by rlouf** [comment]
It's not unorthodox, it's the kind of workflow Blackjax was designed for 🙂

My best guess is that it might be an issue with JAX's cache for jitted functions. I'll take a look, even though @albcab  suggestion works.

**Comment by rlouf** [comment]
Ok so the reason this is happening is that whenever you call `inference_method` in the for loop in your example:

```python
# This is slow, and the memory consumption keeps increasing:
for _ in range(1_000):
    key, rng_key = jax.random.split(key)
    states = inference_loop(rng_key, kernel, state, 1)
```

JAX is re-compiling the one-step function because it is compiled inside the loop. @albcab's suggestion works because JAX's JIT-compilation only happens once outside of the loop.

**Comment by albcab** [comment]
What is interesting is that I thought JAX wouldn't recompile a function if the shape of its parameters didn't change from the first compilation, but it seems that it will if you explicitly call `jax.jit` on it?

**Comment by junpenglao** [comment]
Also, per [jax.scan documentation](https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.scan.html), the inner function is already compiled:
![image](https://user-images.githubusercontent.com/12952641/222231233-366af6e5-d5b5-483e-92a9-493067a215cc.png)

I think constructing the one_step function within another function create a different one in the function scope, thus trigger the recompiling?
