### ISSUE TITLE
Deprecate the "class" approach to the high-level kernels

### ISSUE THREAD

**Issue by rlouf** [blackjax-devs/blackjax#492]
This was introduced to be able to access the low-level step and init functions at the higher level. With hindsight this was neither necessary nor a good design, and it also makes documenting these high-level constructs more complicated. We should use functions instead, like we do for `window_adaptation`.

**Comment by junpenglao** [comment]
Breaking: French dev propose to demolish class. 

Joke aside, what is the proposal for high level API? Factory function that returns callables (init and step)?

**Comment by rlouf** [comment]
Yes. These classes currently serve no purpose other than proposing a shortcut to the lower-level step functions. Factory functions work just fine, and you can still import the lower level ones as e.g. `blackjax.mcmc.hmc.step`.

**Comment by albcab** [comment]
So the idea would be for the user to do 
```python
from blackjax import mcmc
state = mcmc.hmc.init(position)
step = mcmc.hmc.kernel()
new_state, info = step(rng_key, state, logdensity_fn, step_size, inverse_mass_matrix, num_integration_steps)
```
instead of
```python
import blackjax
hmc = blackjax.hmc(logdensity_fn, step_size, inverse_mass_matrix, num_integration_steps)
state = hmc.init(position)
new_state, info = hmc.step(rng_key, state)
```
or do we want to introduce another function that does what classes do now? Maybe in `blackjax.mcmc.hmc.py` intead of `kernels.py`?

Also, this would work for VI, MCMC, SGMCMC, and SMC. But for adaptation algorithms we still need a higher level class or function that puts things together.

**Comment by rlouf** [comment]
I wasn't clear, you would still do:

```python
instead of

import blackjax
hmc = blackjax.hmc(logdensity_fn, step_size, inverse_mass_matrix, num_integration_steps)
state = hmc.init(position)
new_state, info = hmc.step(rng_key, state)
```

except `hmc` would be a function instead of a class.

**Comment by junpenglao** [comment]
So basically `blackjax.hmc` will just return a https://github.com/blackjax-devs/blackjax/blob/2f19d12d428531f6b507530c7a4c9b0ea7ee401d/blackjax/base.py#L88

**Comment by albcab** [comment]
I see how having a class with a `__new__` method that returns an `MCMCSamplingAlgorithm` object is redundant, when we can use a function to directly return that object, and if it makes documenting easier then refactoring is necessary. If all agree I can do the refactoring tomorrow, before new kernels are implemented as a class.

**Comment by rlouf** [comment]
Great, thanks! Then we can start moving these constructors to their respective algorithm-class folder like we discussed.

**Comment by albcab** [comment]
Notice that by replacing classes with functions we loose this alias: `blackjax.mcmc.hmc.kernel`, alias `blackjax.hmc.kernel`.

**Comment by rlouf** [comment]
I'm fine with that
