### ISSUE TITLE
Implement MicroCanoncial Hamiltonian Monte Carlo

### ISSUE THREAD

**Issue by junpenglao** [blackjax-devs/blackjax#530]
### Presentation of the new sampler

- Academic article: https://arxiv.org/abs/2212.08549
- Blog posts: https://statmodeling.stat.columbia.edu/2022/12/20/another-physically-motivated-sampler-microcanonical-hmc/
- Implementations (already in JAX): https://github.com/JakobRobnik/MicroCanonicalHMC

### How does it compare to other algorithms in blackjax?

- Performance: benchmarked to be better than Stan - NUTS

### Where does it fit in blackjax

- has similarity to MEADS, should fit in HMC 

### Are you willing to open a PR?

Maybe

**Comment by reubenharry** [comment]
I am working on the MCHMC codebase (https://github.com/JakobRobnik/MicroCanonicalHMC) and could port their algorithm here.

My main concern is not the algorithm itself, but the tuning, since it has hyperparameters and there is an algorithm to tune them. Would it be possible to incorporate that into BlackJax as well?

**Comment by junpenglao** [comment]
yes they should be incorporate into BlackJax as well

**Comment by albcab** [comment]
I'm not familiar with MCHMC, but the [window adaptation](https://github.com/blackjax-devs/blackjax/blob/main/blackjax/adaptation/window_adaptation.py#L245) for HMC/NUTS could be a good starting point.

**Comment by junpenglao** [comment]
or https://github.com/blackjax-devs/blackjax/blob/main/blackjax/adaptation/meads_adaptation.py, which also have tight integration with the underlying sampler.

**Comment by reubenharry** [comment]
Can now be closed.
