### ISSUE TITLE
Use with Numpyro models notebook not working

### ISSUE THREAD

**Issue by Madhav-Kanda** [blackjax-devs/blackjax#550]
Due to updates in the codebase, the current Numpyro model notebook is not working. I have figured out the changes required to make the code work. Upon going through the repository, I found that there are.md files for examples, but I need to know how you execute them to display the examples in the documentation. Can you please tell me the workflow that needs to be followed before committing the changes?

### Steps/code to reproduce the bug:

```python
import blackjax

num_warmup = 2000

adapt = blackjax.window_adaptation(
    blackjax.nuts, logdensity_fn, target_acceptance_rate=0.8
)
(last_state, parameters), _ = adapt.run(rng_key, initial_position, num_warmup)
kernel = blackjax.nuts(logdensity_fn, **parameters).step
```

### Expected result:

```shell
No error should be displayed!
```

### Error message:

```shell
TypeError                                 Traceback (most recent call last)
Cell In[5], line 8
      3 num_warmup = 2000
      5 adapt = blackjax.window_adaptation(
      6     blackjax.nuts, logdensity_fn, target_acceptance_rate=0.8
      7 )
----> 8 (last_state, parameters), _ = adapt.run(rng_key, initial_position, num_warmup)
      9 kernel = blackjax.nuts(logdensity_fn, **parameters).step

TypeError: window_adaptation..run() takes 2 positional arguments but 3 were given
```

### Blackjax/JAX/jaxlib/Python version information:

```python
BlackJAX 0.9.6
Python 3.10.9 (main, Mar  1 2023, 12:20:14) [Clang 14.0.6 ]
JAX 0.4.10
JAXlib 0.4.10
```

**Comment by junpenglao** [comment]
Sorry about the noise, I forgot that this is in the example in this repo.

Thanks for opening the issue, the instruction is in https://github.com/blackjax-devs/blackjax/blob/0af657a75e7f4207dae272701b1e986bc30db73b/docs/examples/README.md (I will put it back somewhere in the repo)

**Comment by junpenglao** [comment]
Actually, numpyro example should be passing, you need to install from the `main` branch or install `nightly` release.
