### ISSUE TITLE
Moving `max_num_doublings` argument of NUTS from `build_kernel`to `kernel`

### ISSUE THREAD

**Issue by weiyaw** [blackjax-devs/blackjax#564]
### Current behavior

Currently the way to specify `max_num_doublings` is to pass it in the NUTS's `build_kernel()`. This seems to differ from the behaviour in HMC where the `num_integration_steps` goes in the kernel function rather than `build_kernel()`.

The current behavior of NUTS doesn't not allow changing `max_num_doublings` when running adaption steps using e.g. `window_adaption()`, as the NUTS kernel function doesn't take in this argument.

```python
# build adaptation runner
adapt = blackjax.window_adaptation(blackjax.nuts, logprob)

# run adaptation
(_, mcmc_adapted_args), _ = adapt.run(key, init_param)

# build_kernel
kernel = blackjax.nuts(
    logprob, max_num_doublings=max_num_doublings, **mcmc_adapted_args
).step

```

### Desired behavior
Specifying `max_num_doublings` as part of the kernel input, so that this argument can be passed to `window_adaptation()` as part of its `extra_parameters` dictionary.

```python
# build adaptation runner
adapt = blackjax.window_adaptation(
    blackjax.nuts, logprob, max_num_doublings=max_num_doublings
)

# run adaptation
(_, mcmc_adapted_args), _ = adapt.run(key, init_param)

# build_kernel
kernel = blackjax.nuts(logprob, **mcmc_adapted_args).step

```

**Comment by junpenglao** [comment]
Yeah this is a good point, feel free to send a PR
