### ISSUE TITLE
Implement Multiscale Generalized Hamiltonian Monte Carlo with Delayed Rejection

### ISSUE THREAD

**Issue by twiecki** [blackjax-devs/blackjax#577]
### Multiscale Generalized Hamiltonian Monte Carlo with Delayed Rejection

The Stan team is cooking up a new sampler that looks very promising.
Paper (pre-print): https://projecteuclid.org/journals/bayesian-analysis/advance-publication/Delayed-rejection-Hamiltonian-Monte-Carlo-for-sampling-multiscale-distributions/10.1214/23-BA1360.full
Talk: https://www.youtube.com/watch?v=p32zThyo9kY
Slides: https://statmodeling.stat.columbia.edu/wp-content/uploads/2023/09/carpenter-sciml-webinar-2023.pdf

**Comment by albcab** [comment]
Interesting! 

Pretty sure every component of the algorithm is already implemented on blackjax, except the Delayed rejection Metropolis, which should probably go in `proposal.py`.

**Comment by twiecki** [comment]
@albcab Actually there seems to be a paper available already (updated the issue above) in case you're interested.

**Comment by junpenglao** [comment]
Yeah we have this proposal in #368.
