### ISSUE TITLE
Generalizing integrators

### ISSUE THREAD

**Issue by reubenharry** [blackjax-devs/blackjax#587]
### Current behavior

Currently, integrators like `velocity_verlet` use the (euclidean) Hamiltonian form of update for the momentum and position updates. 

### Desired behavior

For some algorithms, it is useful to be able to specify the form of the momentum and position update, but to have the order and size of the steps determined by the integrator. 

For instance, for *any* differential equation of the form:

$$
\frac{d}{dt}f = (\mathcal{O}_1+\mathcal{O}_2)f
$$

the leapfrog operator can be seen as approximating $e^{\epsilon(\mathcal{O}_1 + \mathcal{O}_2)}$ by $e^{\epsilon \mathcal{O}_1/2}e^{\epsilon \mathcal{O}_2}e^{\epsilon \mathcal{O}_1/2}$

(See more here: https://main--zesty-daffodil-572c7d.netlify.app/integrators/)

In a standard Hamiltonian, the forms of $e^{\epsilon \mathcal{O}_2}$ and $e^{\epsilon \mathcal{O}_1}$ are simple, but for other differential equations, they may be more complex. For MCLMC, their forms are given here: https://main--zesty-daffodil-572c7d.netlify.app/choice_of_integrator/#choosing-the-integrator.

For this reason, I propose that we explicitly parametrize all the integrators by the form of the $\mathcal{O}_1$ and $\mathcal{O}_2$ updates. For example:

```python
def leapfrog(O_2, O_1):

  # optionally, something like: O_1 = partial(tree_map(O_1))

  def step(x, u, step_size):

    uu, xx = O_1(step_size * 0.5, u, x)
    uu, xx = O_2(step_size, uu, xx)
    uu, xx = O_1(step_size * 0.5, uu, xx)

    return xx, uu
  
  return step
```

Then by choosing concrete functions for `O_1` and `O_2`, one can instantiate leapfrog for different problems as desired.

(Note: the MCLMC leapfrog roughly resembles the above, but I've made some simplifications, and also made `O_1` and `O_2` return both u (momentum) and x (position), for the sake of uniformity. Also, the logdensity_grad should be passed through, to avoid recalculation. )

**Comment by junpenglao** [comment]
Thanks, we will need to refactor Integrator then. @reubenharry could you update your example with a bit more comments and more descriptive names?

**Comment by reubenharry** [comment]
Updated

**Comment by junpenglao** [comment]
Thanks! I have a better understanding now with your explanation, and also looking at your implmentation in https://github.com/blackjax-devs/blackjax/pull/586/files#diff-d7c8fb39a8f7aa3b3ebfac4fa8cfe8bfc15eef24483d1a767f0caa8b1da91797.

I think we should refactor the general pattern of all the integrators, in a way that [mclachlan](https://github.com/blackjax-devs/blackjax/blob/16df9a6d480f3410347faf678cbe94222386e2bc/blackjax/mcmc/integrators.py#L105) would fit your need (AFAIK this is the same as the `minimal_norm` integrator with the more simple update).

**Comment by albcab** [comment]
+1 to refactoring all integrators. But maybe we should prefix the current integrators with `hamiltonian_velocity_verlet`, which would call the "lower level" `velocity_verlet`, to avoid doing too many changes in algorithms that already use the hamiltonian version of the integrators.
