### ISSUE TITLE
Add progress bar to `run_inference_loop`

### ISSUE THREAD

**Issue by junpenglao** [blackjax-devs/blackjax#610]
We now have a `run_inference_loop` implemented in [here](https://github.com/blackjax-devs/blackjax/pull/598), adding a progress bar would be nice and quite straightforward (see eg: https://github.com/pymc-devs/pymc/commit/c3f93bad3db7c34c12e4c51e1e7fb88f62c97020)

**Comment by PaulScemama** [comment]
@junpenglao sure!
