### ISSUE TITLE
Separate out Halton proposal length from CHEES

### ISSUE THREAD

**Issue by reubenharry** [blackjax-devs/blackjax#620]
### Current behavior

The default length of proposal in dynamic_hmc is drawn at uniform. However, another proposal exists, involving Halton sequences. This actually exists in the blackjax repo, but is hidden away in the CHEES implementation.

### Desired behavior

It would be nice to make it easy to use Halton sequences for dynamic_hmc.

**Comment by junpenglao** [comment]
Maybe we should put dynamic_hmc into its own file, so we can put some of these common choice of dynamic step size generation into the same file.
