### ISSUE TITLE
BlackJAX Paper

### ISSUE THREAD

**Issue by albcab** [blackjax-devs/blackjax#641]
Hi @canyon289, @dfm, @miclegr, @kc611,

We recently wrote a JMLR OSS paper for BlackJAX; you can read the arxived version [here](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Farxiv.org%2Fabs%2F2402.10797&data=05%7C02%7Ccabezasg%40live.lancs.ac.uk%7Ca2d35e26435d48b853f208dc31842d90%7C9c9bcd11977a4e9ca9a0bc734090164a%7C0%7C0%7C638439690967599779%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=KFCl7gwOdhEkw%2B%2FBYLbdrKdUqTQfVX71iwiHU9JOpts%3D&reserved=0). 

You've contributed to the package with new algorithms and/or example notebooks, so we would like to add you as a "technical contributor" to the paper's author list. We will only be able to add your name to the article with your consent, so please let us know if you would or would not like to be included by commenting on this issue.

We'll submit the paper for review this week, so please let us know as soon as possible.

Best,

Alberto, Adrien, Junpeng, Remi

**Comment by canyon289** [comment]
Congratulations, I appreciate the opportunity

**Comment by miclegr** [comment]
Hi! thanks for reaching out, I'm happy to be included in the author list :)
Congratulations on this milestone!

**Comment by kc611** [comment]
Congratulations to you all. 😄 

I'd be happy to be included in the technical authors list.
