### ISSUE TITLE
Add some metadata to integrators and export coefficients

### ISSUE THREAD

**Issue by reubenharry** [blackjax-devs/blackjax#679]
### Current behavior

There's no way to currently obtain the number of gradient calls for a given integrator. 

Also, it is sometimes useful to have the integrator coefficients, and these aren't exported from `integrators.py`.

### Desired behavior

Functions like:

```python
def calls_per_integrator_step(c):
    if c==velocity_verlet_coefficients: return 1
    if c==mclachlan_coefficients: return 2
    if c==yoshida_coefficients: return 3

    else: raise Exception

def name_integrator(c):
    if c==velocity_verlet_coefficients: return "velocity_verlet"
    if c==mclachlan_coefficients: return "mclachlan"
    if c==yoshida_coefficients: return "yoshida"

    else: raise Exception
```

Also, to export the coefficients.

**Comment by junpenglao** [comment]
Per #681, we need some other ways to expose this information. 

How about assigning the property to the return integrator object? We can type integrators as Protocal.

**Comment by reubenharry** [comment]
Yes, I think that would be good. The info we want attached is:

1. Order of the integrator
2. Number of grad calls 
3. Name
4. Type (isokinetic or mclachlan)
5. The integrator itself (this could be a function of "isokinetic" or "euclidean", if you think that's a reasonable design decision

**Comment by junpenglao** [comment]
I think the decision ultimately tie to how these information is used in the library beyond benchmarking. Let's circle back when you have some examples.
