### ISSUE TITLE
New jax keys

### ISSUE THREAD

**Issue by reubenharry** [blackjax-devs/blackjax#703]
### Current behavior

We currently use jax.random.PRNGKey throughout.

### Desired behavior

Following this jax discussion https://jax.readthedocs.io/en/latest/jep/9263-typed-keys.html, I'm wondering if we want to switch to the new key style, jax.random.key

**Comment by junpenglao** [comment]
We are already using the new random key: https://github.com/blackjax-devs/blackjax/pull/569. It is just we still call the custom type PRNGKey
