### ISSUE TITLE
Implement Waste-free SMC

### ISSUE THREAD

**Issue by ciguaran** [blackjax-devs/blackjax#710]
https://arxiv.org/abs/2011.02328

**Comment by AdrienCorenflos** [comment]
This is already implemented (and the default I think)
https://github.com/blackjax-devs/blackjax/blob/f8db9aa04d83fed4b3bde0f37ddf6194b229308f/blackjax/smc/base.py#L115
Is this not properly documented?

**Comment by ciguaran** [comment]
The thing is that in the current state is not super usable since you can only use it from base.py. In other words, tempered and adaptive tempered are coupled to the classic SMC case (iterate MCMC and take the last sample).
