### ISSUE TITLE
first example in quickstart.md missing Jacobian adjustment

### ISSUE THREAD

**Issue by bob-carpenter** [blackjax-devs/blackjax#750]
### Describe the issue as clearly as possible:

In the documentation markdown [docs/examples/quickstart.md](https://github.com/blackjax-devs/blackjax/blob/b107f9fd60cfc1261a5ce35690b1d0f141041c07/docs/examples/quickstart.md?plain=1#L14), which renders as https://blackjax-devs.github.io/blackjax/examples/quickstart.html, the first example is missing the Jacobian adjustment for the change of variables, so it's not giving the correct log density on the unconstrained scale. 

### Steps/code to reproduce the bug:

```python
The log density in question is this:


def logdensity_fn(loc, log_scale, observed=observed):
    """Univariate Normal"""
    scale = jnp.exp(log_scale)
    logpdf = stats.norm.logpdf(observed, loc, scale)
    return jnp.sum(logpdf)
```

### Expected result:

```shell
I expected this, with the log Jacobian adjustment included on the log scale.  For the transform $y = \exp(x)$, the log Jacobian adjustment is just $\log \exp'(x) = x$.


def logdensity_fn(loc, log_scale, observed=observed):
    """Univariate Normal"""
    scale = jnp.exp(log_scale)
    logjac = log_scale
    logpdf = stats.norm.logpdf(observed, loc, scale)
    return logjac + jnp.sum(logpdf)
```

### Error message:

```shell
You won't get an error message, just the wrong answer.  Without the log Jacobian, you get an implicit prior due to leaving out the log scale correction.  With the Jacobian adjustment, you get a uniform prior over the constrained support of the scale parameter.
```

### Blackjax/JAX/jaxlib/Python version information:

```python
This is the web-facing site as of October 29, 2024.
```

### Context for the issue:

I think it should be prioritized because it's the very first example.  If you don't want to get into this complexity, you could switch to an example without a change of variables.

**Comment by junpenglao** [comment]
Ah that's a great point - thanks Bob!
