### ISSUE TITLE
`requirements-dev.txt` version of deps

### ISSUE THREAD

**Issue by junpenglao** [blackjax-devs/blackjax#82]
Is the version for deps in `requirements-dev.txt` necessary? Can we remove them?

**Comment by rlouf** [comment]
It's just to make sure that CI and local tests run on the exact same version of these libraries. The probability of a mismatch happening is low, but can still happen if people don't update their environment frequently. What's your opinion ?

**Comment by rlouf** [comment]
The introduction of `pre-commit` makes all dependencies but `pre-commit` and what is needed for tests unnecessary. Waiting for #31 to be merged to clean `requirements-dev.txt`. We should keep the version numbers to make sure the checks/tests ran locally by developers are the same than the ones ran in CI.
